version: '3.8'

services:
    db:
        image: postgres:17-alpine
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_ROOT_PASSWORD: root_password
            TZ: "Europe/Moscow"
        ports:
            - "${POSTGRES_PORT}:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 30s
            timeout: 2s
            retries: 5
        volumes:
            - ./docker/pgdata:/var/lib/postgresql

    web:
        container_name: web
        restart: unless-stopped
        build:
            context: .
        command: make start
        environment:
            TZ: "Europe/Moscow"
        ports:
            - "8080:8000"
        volumes:
            - ".:/app"
            - "/tmp:/tmp"
        depends_on:
            -  db
