# Версия docker-compose
version: '3.8'
# Список наших сервисов (контейнеров)
services:
    postgresql:
        image: postgres:latest
        container_name: postgres
        restart: unless-stopped
        tty: true
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
            TZ: "Europe/Moscow"
        ports:
            - "5430:5432"
        volumes:
            - ./docker/pgdata:/var/lib/postgresql/data/pgdata
    web:
        container_name: web
        restart: unless-stopped
        tty: true
        build:
            context: .
        command: make start
        environment:
            TZ: "Europe/Moscow"
        ports:
            - "8080:8000"
        volumes:
            - ".:/app"
            - "/tmp:/tmp"
        depends_on:
            - postgresql
        links:
            - postgresql

volumes:
    pgdata:
        driver: local

