# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    web:
        build:
            context: .
        command: make start
        ports:
            - "8080:8080"
        volumes:
            - ".:/app"
            - "/tmp:/tmp"
